# Use the official Python image as a base
FROM python:3.9  # or your desired Python version

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code
COPY . .

# Command to run your application
CMD ["python", "consumer.py"]  # Change to producer.py when needed

